name: Deploy CoinsPaidNovember
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout coinspaidnovember
        uses: actions/checkout@v4
        with:
          repository: newsuperdudes/coinspaidnovember
          token: ${{ secrets.GH_PAT }}
      - name: Deploy to /coinspaidnovember via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /coinspaidnovember/
          local-dir: ./
          dangerous-clean-slate: true
          timeout: 600000
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
