name: Deploy Nebius Tech
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nebiustech
        uses: actions/checkout@v4
        with:
          repository: newsuperdudes/nebiustech
          token: ${{ secrets.GH_PAT }}
      - name: Deploy to /nebiustech via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /nebiustech/
          local-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
